version: '3'
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  simulator:
    build: ./simulator
    depends_on:
      - broker

  dashboard:
    build: ./dashboard
    ports:
      - "5000:5000"
    depends_on:
      - broker
